//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagazineSalesProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Invoice
    {
        [Key]
        public int InvoiceNumber { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string CardNumber { get; set; }
        public Nullable<int> ExpirationMonth { get; set; }
        public Nullable<int> ExpirationYear { get; set; }
        public int SellerID { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Seller Seller { get; set; }
        public virtual Magazine Magazine { get; set; }
    }
}
