//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagazineSalesProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceContain
    {
        public int InvoiceNumber { get; set; }
        public int MID { get; set; }
        public int ContainsKey { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Magazine Magazine { get; set; }
    }
}
